# Copyright 2019 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _APPNAME: gpu-accel-webrtc
  _USERNAME: webrtc
  _PROVISION_ZONE: us-central1-f
  _SOURCE_IMAGE_FAMILY: ubuntu-1910
steps:
  - name: ubuntu
    id: "create_image_spec"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cat <<END>packer.json
        {
        "builders": [
            {
            "type": "googlecompute",
            "state_timeout": "30m",
            "project_id": "$PROJECT_ID",
            "zone": "${_PROVISION_ZONE}",
            "machine_type": "n1-standard-8",
            "disk_size": "50",
            "source_image_family": "${_SOURCE_IMAGE_FAMILY}",
            "image_name": "${_APPNAME}-{{timestamp}}",
            "image_family": "${_APPNAME}",
            "ssh_username": "${_USERNAME}",
            "scopes": [
                "https://www.googleapis.com/auth/userinfo.email",
                "https://www.googleapis.com/auth/compute",
                "https://www.googleapis.com/auth/devstorage.full_control"
            ]
            }
        ],
        "provisioners": [
          {
            "type": "shell",
            "inline": ["mkdir -p /home/${_USERNAME}/gpu-accel-webrtc/gce"]
          },
          {
            "type": "file",
            "source": "./",
            "destination": "/home/${_USERNAME}/gpu-accel-webrtc/gce"
          },
          {
            "type": "shell",
            "inline": ["sudo cp /home/${_USERNAME}/gpu-accel-webrtc/gce/config/webrtc.env /etc/webrtc.env"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/install_desktop.sh"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/install_nvidia_driver.sh"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/install_3D_demos.sh"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/install_docker.sh"]
          },
          {
            "type": "shell",
            "inline": ["sudo cp /home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/start_webrtc.sh /usr/local/bin/start_webrtc"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/install_webrtc.sh"]
          },
          {
            "type": "shell",
            "inline": ["/home/${_USERNAME}/gpu-accel-webrtc/gce/scripts/pull_images.sh"]
          }
        ]
        }
        END

  - name: "gcr.io/$PROJECT_ID/packer"
    args:
      - build
      - -force
      - -var
      - project_id=$PROJECT_ID
      - packer.json
